classes_existentes = ['CONSTITUCIONAL', 'ADMINISTRATIVO', 'ELEITORAL', 'CONSUMIR', 'NOTARIAL E REGISTRAL',
                      'DA CRIANÇA E ALESCENTE', 'EMPRESARIAL', 'AMBIENTAL', 'PROCESSUAL CIVIL', 'PENAL',
                      'PROCESSUAL PENAL', 'PENAL E PROCESSUAL PENAL MILITAR', 'TRIBUTÁRIO', 'PREVIDENCIÁRIO',
                      'INTERNACIONAL', 'TRABALHO E PROCESSUAL TRABALHO', 'SÚMULAS STF E STJ POR ASSUNTO', 'CIVIL']
